---
title: "R Notebook"
output: html_notebook
---

```{r}

# Set the working Directory
setwd("/home/david/Desktop/DataAnalysisProjects/FlightDelays")

# Read in Data
flight_data_full = read.csv('data/flight_2003_2017.csv', header = TRUE)


# Take out unused variables
flight_data <- subset(flight_data_full, 
                      select = -c(X.month, airport, airport_name, X.arr_delay, 
                                  X.carrier_delay, weather_delay, nas_delay, 
                                  security_delay, late_aircraft_delay, X, 
                                  carrier))

# Keep year and carrier_name and sum all similar columns
flight_data_shaped <- aggregate(.~year+carrier_name, flight_data, sum)

# Generate functions to find percents for specific variables

flight_data_percent <- flight_data_shaped

# Carriers on_time
flight_data_percent$On_Time <- 
  (flight_data_percent$arr_flights - flight_data_percent$arr_del15 - 
     flight_data_percent$arr_cancelled - flight_data_percent$arr_diverted ) / 
    flight_data_percent$arr_flights * 100


# Remove columns no longer used
flight_data_percent_shaped <- subset(flight_data_percent, 
                      select = -c(arr_flights, arr_del15, carrier_ct, 
                                  X.weather_ct, nas_ct, security_ct, 
                                  late_aircraft_ct, arr_cancelled, 
                                  arr_diverted))


# Not all years are present for each airline
# Create rows for carriers that had no data for that year (fill with 0's)






# generate table with all years wanted by unique carrier names

# fill in missing rows and make N/A values zero 




# change to shorter name for calculation readibility



# Remove columns no longer used


# Change years from int to factor
df <- flight_data_percent_shaped
df$year <- factor(df$year)

# rename level for later graphing ease
levels(df$carrier_name)[levels(df$carrier_name) == 'ATA Airlines d/b/a ATA'] <- 'ATA Airlines'

# rename carrier_name
names(df)[names(df) == 'carrier_name'] <- 'Carrier Name'
names(df)[names(df) == 'year'] <- 'Year'
names(df)[names(df) == 'On_Time'] <- 'On Time'

```


```{r}
# Write to csv
write.csv(df, file = "data/flight_data_ontime.csv", row.names = FALSE)

```





